var deck={
  "AoS": {points:1, img:"./img/Spades/AofS"},
  "2oS": {points:2, img:"./img/Spades/2ofS"},
  "3oS": {points:3, img:"./img/Spades/3ofS"},
  "4oS": {points:4, img:"./img/Spades/4ofS"},
  "5oS": {points:5, img:"./img/Spades/5ofS"},
  "6oS": {points:6, img:"./img/Spades/6ofS"},
  "7oS": {points:7, img:"./img/Spades/7ofS"},
  "8oS": {points:8, img:"./img/Spades/8ofS"},
  "9oS": {points:9, img:"./img/Spades/9ofS"},
  "10oS":{points:10, img:"./img/Spades/10ofS"},
  "JoS": {points:10, img:"./img/Spades/JofS"},
  "QoS": {points:10, img:"./img/Spades/QofS"},
  "KoS": {points:10, img:"./img/Spades/KofS"},
  "AoH": {points:1, img:"./img/Hearts/AofH"},
  "2oH": {points:2, img:"./img/Hearts/2ofH"},
  "3oH": {points:3, img:"./img/Hearts/3ofH"},
  "4oH": {points:4, img:"./img/Hearts/4ofH"},
  "5oH": {points:5, img:"./img/Hearts/5ofH"},
  "6oH": {points:6, img:"./img/Hearts/6ofH"},
  "7oH": {points:7, img:"./img/Hearts/7ofH"},
  "8oH": {points:8, img:"./img/Hearts/8ofH"},
  "9oH": {points:9, img:"./img/Hearts/9ofH"},
  "10oH":{points:10, img:"./img/Hearts/10ofH"},
  "JoH": {points:10, img:"./img/Hearts/JofH"},
  "QoH": {points:10, img:"./img/Hearts/QofH"},
  "KoH": {points:10, img:"./img/Hearts/KofH"},
  "AoC": {points:1, img:"./img/Clubs/AofC"},
  "2oC": {points:2, img:"./img/Clubs/2ofC"},
  "3oC": {points:3, img:"./img/Clubs/3ofC"},
  "4oC": {points:4, img:"./img/Clubs/4ofC"},
  "5oC": {points:5, img:"./img/Clubs/5ofC"},
  "6oC": {points:6, img:"./img/Clubs/6ofC"},
  "7oC": {points:7, img:"./img/Clubs/7ofC"},
  "8oC": {points:8, img:"./img/Clubs/8ofC"},
  "9oC": {points:9, img:"./img/Clubs/9ofC"},
  "10oC":{points:10, img:"./img/Clubs/10ofC"},
  "JoC": {points:10, img:"./img/Clubs/JofC"},
  "QoC": {points:10, img:"./img/Clubs/QofC"},
  "KoC": {points:10, img:"./img/Clubs/KofC"},
  "AoD": {points:1, img:"./img/Diamonds/AofD"},
  "2oD": {points:2, img:"./img/Diamonds/2ofD"},
  "3oD": {points:3, img:"./img/Diamonds/3ofD"},
  "4oD": {points:4, img:"./img/Diamonds/4ofD"},
  "5oD": {points:5, img:"./img/Diamonds/5ofD"},
  "6oD": {points:6, img:"./img/Diamonds/6ofD"},
  "7oD": {points:7, img:"./img/Diamonds/7ofD"},
  "8oD": {points:8, img:"./img/Diamonds/8ofD"},
  "9oD": {points:9, img:"./img/Diamonds/9ofD"},
  "10oD":{points:10, img:"./img/Diamonds/10ofD"},
  "JoD": {points:10, img:"./img/Diamonds/JofD"},
  "QoD": {points:10, img:"./img/Diamonds/QofD"},
  "KoD": { points:10, img:"./img/Diamonds/KofD"},
}

console.log(deck["7oD"])